name: eatwise
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  get: ^4.7.3
  dio: ^5.9.1
  get_storage: ^2.1.1
  intl: ^0.20.2
  mobile_scanner: ^7.1.4
  flutter_dotenv: ^6.0.0
  flutter_screenutil: ^5.9.3
  google_fonts: ^8.0.1
  flutter_svg: ^2.2.3
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/Logo-peanut.png"
  min_sdk_android: 21
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/images/launcher_ic_logo.png"
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/
